
spring:
  application:
    name: shoping-index
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka,http://127.0.0.1:8001/eureka,http://127.0.0.1:8002/eureka
feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'